apiVersion: v1
kind: Pod
metadata:
  name: pod-node-selector-1
  labels:
    tier: web
    type: nginx
spec:
  containers:
  -  name: mynginx
     image: nginx:1.20.1
  nodeSelector:
    env: prod
    type: linux
