apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - name: cache-volume
      mountPath: /test
  volumes:
  - name: cache-volume
    emptyDir: {}
