apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod-1001
spec:
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', "echo hello && sleep 5000"]

