apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-petclinic-with-delay120
spec:
  containers:
  - name: liveness
    image: malleshdevops/petclinic:spring-k8s
    ports:
    - name: liveness-port
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: liveness-port
      initialDelaySeconds: 120
      periodSeconds: 5

