apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-petclinic-named-port-without-probe
spec:
  containers:
  - name: liveness
    image: malleshdevops/petclinic:spring-k8s
    ports:
    - name: liveness-port
      containerPort: 8080
