apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod-security
  labels:
    app: nginx-web
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  securityContext:
    runAsUser: 1000
    fsGroup: 1000 

