apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  -  name: mynginx
     image: nginx:1.20.1
     ports:
     - containerPort: 80
  -  name: jenkins
     image: jenkins/jenkins:lts
     ports:
     - containerPort: 8080
