apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo-failure
  namespace: dev
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "3Gi"
        cpu: "800m"
      requests:
        memory: "2Gi"
        cpu: "400m"

