apiVersion: v1
kind: Pod
metadata:
  name: react-app
  namespace: dev
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: malleshdevops/devops20:reactjs-v1
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"

